### ISSUE TITLE
Super Slowness

### ISSUE THREAD

**Issue by infabo** [danslo/Danslo_Aop#1] opened 2016-03-04 10:02 UTC
Dear Daniel!

I have noticed massive slowdown of a Magento since a few days.
I traced it down to this extension.
I first disabled my custom aspects extension to be sure, that none of my aspects are causing the slowdowns.
I figured out, that simply having danso_aop installed is enough to get Magento from 400ms response to something up to 12 seconds (4secs at min). This is at least an increase by factor 10 in pageload terms (in the 4secs case).
I have seen, goap framework 1.0.0 stable has been released 20 days ago. It may be related to this update.
I have observed, the file var/cache/aop/_transformation.cache gets updated/changed on every Magento page-load. AOP-cache is enabled in Magento. Can it be the cause?

I'm not familiar with it, so can you please have a look whether you can reproduce the issue on your side?
Thank you.

**Comment by infabo** [comment] 2016-03-04 10:33
Switching back to goap/framework 1.0.0 (instead of 1.0.1 - which released 5 days ago) fixed it.
So it is definitely not related to the Magento extension i guess.

**Comment by lisachenko** [comment] 2016-03-04 10:44
Hello, It's very strange, actually 1.0.0..1.0.1 of `goaop/framework` doesn't contain any significant changes. There are many changes for 2.x-dev branch that can slow down the first analysis of code (due to the switch to nikic/PHP-Parser library), but there are no stable releases for that.

If `var/cache/aop/_transformation.cache` is updated every time, then something go wrong in initialization/configuration of AOP and kernel tries to process several files one more time instead of using just cached version of source code. Could you please, put a breakpoint in the `\Go\Instrument\ClassLoading\CachePathManager::flushCacheState` method and dump the variable `$this->newCacheState` (please skip a first request and show the result for second page refresh)

**Comment by infabo** [comment] 2016-03-04 12:02
OK, I'll xdebug it later today.

**Comment by infabo** [comment] 2016-03-04 12:18
PS:
I can confirm, on 1.0.0 the change-timestamp on the file var/cache/aop/_transformation.cache gets updated too. But without any performance penalties.

**Comment by lisachenko** [comment] 2016-03-06 14:19
@infabo are there any new details? I can't found anything suspicious in the source code...

**Comment by infabo** [comment] 2016-03-07 13:15
@lisachenko not yet. I didn't have time yet

**Comment by danslo** [comment] 2016-03-07 14:32
Hey @infabo , do you have a specific Aspect that is causing this, or is having this extension installed enough to cause this slowness?

**Comment by danslo** [comment] 2016-03-07 14:38
Nevermind, I can sort of reproduce it myself now. Just installing it with 1.0.1 takes me from 400ms to 1.4s. Not exactly as drastic as what you see, but still something odd is going on. I'll try to make a profile dump.

**Comment by danslo** [comment] 2016-03-07 14:50
Seems to be because we pass class paths directly to ``FilterInjectorTransformer::rewrite``, which does check if a file is cached but seemingly never caches files anymore (cache directory stays empty, even after succesful CachingTransformer operations). Any thoughts @lisachenko?

**Comment by danslo** [comment] 2016-03-07 15:20
Okay, I traced it down to this bit:

In `Go\Instrument\Transformer\CachingTransformer::transform` in 1.0.0 it does:

``` php
if ($cacheModified < $lastModified 
    || !$this->container->isFresh($cacheModified)) {
```

And in 1.0.1 it does:

``` php
if ($cacheModified < $lastModified
    || $cacheState['cacheUri'] !== $cacheUri
    || !$this->container->isFresh($cacheModified)
) {
```

However, for all files `$cacheState['cacheUri']` seems to be `null`. So the check becomes true and it will run `processTransformers` instead of using the original class.

Git blame points to this this pull request:
https://github.com/goaop/framework/pull/258

Not sure why though.

**Comment by lisachenko** [comment] 2016-03-07 20:25
@danslo thank you very much for researching this bug! I was working on cache revalidation for symfony2 applications and cache warming can occurs for several times in it, so I decided to put this check. To keep logic correct there should be expression like this: `|| (isset($cacheState['cacheUri']) && $cacheState['cacheUri'] !== $cacheUri)` But I should recheck this one more time...

**Comment by lisachenko** [comment] 2016-03-08 07:06
Released patch version 1.0.2 of `goaop/framework`. Thanks @infabo and @danslo

**Comment by infabo** [comment] 2016-03-08 08:23
@lisachenko and @danslo Thanks for investigating. Cool to see the bug has already been found. Just had time to look into it and now it's already solved. :D

@lisachenko 
I put a breakpoint in \Go\Instrument\ClassLoading\CachePathManager::flushCacheState method.
On the first request, it is an array of over 200 items with file-paths. On the second request it has only 3 items in there and for the third request and onwards the $this->newCacheState remains empty.
Think this is how it should behave (nothing new to flush to cache-file anymore), right?

**Comment by infabo** [comment] 2016-03-08 08:30
Can confirm: 1.0.2 of goaop/framework and no more issues.

**Comment by infabo** [comment] 2016-03-08 08:38
And yes: I have experienced on another shop - just checked it now before I updated from 1.0.1 to 1.0.2:
For example a drop from over 8sec load-time of the HTML-document to ~800ms on /admin/admin/cache/index (chrome network profiler).

**Comment by lisachenko** [comment] 2016-03-08 11:23
> On the first request, it is an array of over 200 items with file-paths. On the second request it has only 3 items in there and for the third request and onwards the $this->newCacheState remains empty.
> Think this is how it should behave (nothing new to flush to cache-file anymore), right?

Yes, it's correct behaviour, there should be no extra checks in runtime when cache is ready.

> Can confirm: 1.0.2 of goaop/framework and no more issues.

Great!

> For example a drop from over 8sec load-time of the HTML-document to ~800ms on /admin/admin/cache/index (chrome network profiler).

@infabo could you show the timing of your applications without AOP enabled? Is ~800ms can be compared to the mode without AOP?
I have a bad feeling, that AOP in your instance can be working in the debug mode even for production. Thus, engine is checking all filemtimes and increase the time-to-load value.

**Comment by danslo** [comment] 2016-03-10 00:50
With this extension, debug [is only enabled](https://github.com/danslo/Danslo_Aop/blob/master/code/Model/Observer.php#L58) when Magento developer mode is enabled, or when AOP cache type is set to Disabled in the Magento backend.

edit:
And as it appeared to have been fixed, I'll close this. Thanks guys!

**Closed as completed** 2016-03-10 00:50 UTC

**Comment by infabo** [comment] 2016-03-24 08:29
Hard to measure, can't do "ab" on a Magento backend page.
But it seems like on my super-slow dev-machine the loading time for just the HTML on System->Cache increases from ~740ms to ~940ms after just enabling Danslo_Aop. Xdebugged it, and debug is false for the aspect kernel. Seems to be related to goaop and not this Magento extension though.
